### ISSUE TITLE
Feature: provide suggestions if no definitions found

### ISSUE THREAD

**Issue by SevereOverfl0w** [jams2/py-dict-client#2]
```
kindle-to-anki ❯ curl dict://dict.org/m:behooves
220 pan.alephnull.com dictd 1.12.1/rf on Linux 4.4.0-1-amd64 <auth.mime> <140874701.29398.1600291839@pan.alephnull.com>
250 ok
152 2 matches found
gcide "Behoove"
gcide "Behooved"
.
250 ok [d/m/c = 0/2/20624; 0.000r 0.000u 0.000s]
221 bye [d/m/c = 0/0/0; 0.000r 0.000u 0.000s]
```

I have some words in my set which aren't able to be read, but the server has suggestions of what they might be.  It would be great if I could get these back and use them instead of just getting None.

**Comment by jams2** [comment]
This was already implemented but due to an oversight on my part unusable - to get the response shown by curl, you need to specify "." as the match strategy (now the default, was "exact"). "." defers to the server's default strategy.
