### ISSUE TITLE
Support words with <SPC>, <">, <'>,  and <\> in them as per RFC 2229

### ISSUE THREAD

**Issue by kamyabzad** [jams2/py-dict-client#9]
[RFC 2229: A Dictionary Server Protocol](https://datatracker.ietf.org/doc/html/rfc2229#section-2.2) specification supports words with <SPC>, <">, <'>,  and <\>, and all the dictionaries I've used (wikt-en-all, foldoc, gcide, ...) contains words like that, but the current implementation doesn's support this. I will open a pull request to fix this. Please let me know if you have any suggestions!
- Thanks for the library!

**Comment by jams2** [comment]
Released in 0.2.0, thanks for your contribution @kamyabzad !
